### ISSUE TITLE
Furnace AIR crafting ERROR

### ISSUE THREAD

**Issue by xalixilax** [WolfyScript/CustomCrafting-Wiki#11]
**Describe the bug**
Error spam in the console

**To Reproduce**
Put a furnace down
Add 1 coal and 1 log in the furnace
When the log is done smelting, the error below pop up in the console

**Server**
 - Paper 1.16.5 git-Paper-"809466f2e"
 - Java 8
 - wolfyutilities v.1.6.3.25
 - custom crafting v.1.6.5.1.3

**Additional context**
`04.05 13:12:20 [Server] ERROR Could not pass event FurnaceSmeltEvent to CustomCrafting v1.6.5.1.3
04.05 13:12:20 [Server] INFO java.lang.IllegalArgumentException: Recipe must have non-AIR result.
04.05 13:12:20 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:46) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:19) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:23) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:53) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:32) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.inventory.RecipeIterator.next(RecipeIterator.java:41) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.inventory.RecipeIterator.next(RecipeIterator.java:12) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getRecipesFor(CraftServer.java:1335) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.Bukkit.getRecipesFor(Bukkit.java:800) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at me.wolfyscript.customcrafting.listeners.FurnaceListener.onSmelt(FurnaceListener.java:162) ~[?:?]
04.05 13:12:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor574.execute(Unknown Source) ~[?:?]
04.05 13:12:20 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.TileEntityFurnace.burn(TileEntityFurnace.java:399) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.TileEntityFurnace.tick(TileEntityFurnace.java:352) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:864) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:683) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1486) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
04.05 13:12:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

**Comment by WolfyScript** [comment]
ok, interesting... that shouldn't happen at all. 
There is one crafting recipe that has an empty result. 
Do you have any other plugin that registers recipes?

**Comment by xalixilax** [comment]
Yes I am using itemsadder. Also it was a fresh install from custom crafting. I have no registered recipe yet. I have some furnace recipe with itemsadder
