### ISSUE TITLE
Workbench issue

### ISSUE THREAD

**Issue by keepofthehause** [WolfyScript/CustomCrafting-Wiki#12]
**Describe the bug**
Crafting table recipes often don't load correctly. It's saving correctly and I can find it in the folder, but the item does not show up correctly in the recipe list and can not be crafted. Seems to mostly affect shaped recipes, shapeless recipes work fine.

**To Reproduce**
1. Create a workbench recipe
2. Check your recipe book
3. Try to craft the item

**Expected behavior**
The item should just appear correctly in the recipe list and be able to be crafted

**Screenshots**
[imgur link](https://imgur.com/a/sbWOpSR)

**Server (please complete the following information):**
 - Server Software: Spigot
 - Minecraft version: 1.17
 - Java version: 16

**Comment by WolfyScript** [comment]
This update should fix the issue:
https://www.spigotmc.org/resources/wolfyutilities-core-plugin-api-1-14-1-17.64124/update?update=408175
