### ISSUE TITLE
Custom brewing stand recipes can't have a base potion set

### ISSUE THREAD

**Issue by RaizaTakimaru** [WolfyScript/CustomCrafting-Wiki#15]
**Describe the bug**
I enabled making custom brewing recipes on my server, however I cannot set the base potion(s). This results in any potion being accepted.
The spot that is circled in the screenshot I expect to have been an empty spot, not a grey stained pane.
This is on CC 1.6.6.0f and WU 1.6.4.2

**To Reproduce**
1. Enable custom brewing recipes if not yet so.
2. Use command /cc to open general interface.
3. Click the brewing stand to make a new recipe.
4. The spot in the first column, fifth from the top, is a grey stained pane.

**Expected behavior**
The mentioned spot in step 4 should be empty, to allow a base potion to be put in.

**Screenshots**
![image](https://user-images.githubusercontent.com/83662707/123519553-4c6f1780-d6ac-11eb-8c1b-31c379f8ab99.png)

**Server (please complete the following information):**
 - Server Software: Paper
 - Minecraft version 1.16.5
 - Java version Java 11

**Comment by WolfyScript** [comment]
Fixed in CustomCrafting v1.7.0.2.
I'll keep this issue open until the free public version is out.

**Comment by YKDZ** [comment]
> Fixed in CustomCrafting v1.7.0.2.
> I'll keep this issue open until the free public version is out.

Will you fix this in a version that supports Java 11? I think a lot of people need custom recipes on the brewing table. After fixing this problem, it will become the best custom recipe plugin in 1.16.5.
