### ISSUE TITLE
Console Spam error 529

### ISSUE THREAD

**Issue by kena73** [WolfyScript/CustomCrafting-Wiki#18]
**Describe the bug**
Constant console spam

**To Reproduce**
Unfortunately no idea how to reproduce

**Expected behavior**
For there to not be console spam

**Log**
https://mcpaste.io/dd5112ab3c6070ea

**Server (please complete the following information):**
 - Paper 1.17.1
 - Latest version of CC and WU
 - Java 16

**Additional context**
Plugin seemingly randomly started flooding console with the error

**Comment by WolfyScript** [comment]
Fixed in CustomCrafting 1.7.1.1 https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/update?update=413142
