### ISSUE TITLE
Recipe book gives exp

### ISSUE THREAD

**Issue by GuazP** [WolfyScript/CustomCrafting-Wiki#26]
**Describe the bug**
Idk if that's still the case because I used outdated version, but recipe book is possible to grindstone what gives user xp back, it might be big flaw if crafting isn't restriced and free to take by command or something like that.

**To Reproduce**
Just follow screen at grindstone:
![image](https://user-images.githubusercontent.com/33330881/126297617-1b3ece05-d81c-4cb7-8696-99f9d04812e6.png)

**Expected behavior**
Atleast experience shouldn't pop out.

**Screenshots**
put at 'to reproduce'

**Server (please complete the following information):**
 - Server Software: Purpur
 - Minecraft version: 1.16.5
 - Java version: Java 8

**Comment by WolfyScript** [comment]
Which version of CustomCrafting are you using?
I tested it, and I am not able to place it into the grindstone. You can only place it in if a recipe is associated with that item.
So seems like it is fixed.

**Comment by GuazP** [comment]
I see, okay 👍 

Just in case I modified that book a little -> Generally I disabled crafting it. 
Maybe that impact behaviour, but might be fixxed as well, anyway new version isn't for me yet :)
