### ISSUE TITLE
When i type /recipes edit test get this error on console

### ISSUE THREAD

**Issue by SNokerYT** [WolfyScript/CustomCrafting-Wiki#31]
**Describe the bug**

When i type /recipes edit test get this error on console
also, I can't found the recipe that I make
https://pastebin.com/qtXStFVj

**Server (please complete the following information):**
 - Server Software [Paper]
 - Minecraft version [1.16.5]
 - Java version [Java 16]

**Comment by WolfyScript** [comment]
Ok I see.... There are two different errors.
One, when using the `/recipes edit test:3` and then one when using `/recipes edit test`.

The first command (`/recipes edit test:3`) is the correct usage... but fails. I will fix that.
For now, you could use the **Recipe List** on the main menu, on the bottom right, and find your recipe to edit it.
