### ISSUE TITLE
customcrafting does not work

### ISSUE THREAD

**Issue by wolf0023** [WolfyScript/CustomCrafting-Wiki#32]
**Describe the bug**
CustomCrafting does not work due to the errors with 'null'

**To Reproduce**
1, install latest customcrafting and wolfyutilities to your server
2, start the server
3, you will see the errors like screenshot below

**Screenshots**
https://gyazo.com/f1b79bd9c85096ed4482b11d47a01bd0

**Server**
Server Software: Paper
Minecraft version: 1.16.5
Java version: 16

**Comment by WolfyScript** [comment]
It looks like the `recipe_book.json` is corrupted. Deleting that file should fix it. 
(Or if you edited it, make sure you have no missing symbols like commas, brackets, or quotation marks)

**Comment by wolf0023** [comment]
Thank you so much :)
