### ISSUE TITLE
Random Results don't work in Cauldron recipes

### ISSUE THREAD

**Issue by Xiao-MoMi** [WolfyScript/CustomCrafting-Wiki#37]
**Describe the bug**
When I shift+right add many results to Cauldron recipe, I found the result to be the same unless I reload the plugin.

**Server (please complete the following information):**
 - purpur-1.17.1-1308
 - Minecraft version 1.17.1
 - Java 16

**Comment by WolfyScript** [comment]
Thanks for the report, I found the issue. It will be fixed soon.
