### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by Snozbear** [WolfyScript/CustomCrafting-Wiki#41]
Occasionally the plugin will just decide to stop working, and prevent the server from loading any further or stopping, and requires a hard kill to stop the server. To fix you need to delete everything in the CC plugin folder and start fresh.

I can't find a way to reliably reproduce the error. The first time we got this issue was because we were trying to reload the plugin,  decided to stop doing that but this time it has showed up after a regular restart. 
 
https://paste.dedimc.io/iterunozos.md

Sorry theres not much info but thats really all it shows in regards to CC. 

Using the most updated Java 16, Wolfy and CC on Paper 1.17.1

**Comment by WolfyScript** [comment]
Have you edited the recipe book in any way?

**Comment by Tnology** [comment]
https://pastebin.com/raw/k4TuJvcZ
I have the same issue. The first time in the console it said something about the recipe book already existing so I deleted it and this is (I think) the exact same error as I had before. The recipe book file just said "null" in it so I thought it was fine to delete.
EDIT: Weird, so apparently deleting that file made it work but the errors still appear in console. The plugin seems to work fine so ignore this.

**Comment by Snozbear** [comment]
> Have you edited the recipe book in any way?

We've been adding recipes via the in-game commands/gui but other than that we haven't messed around with anything.
