### ISSUE TITLE
Custom smelting recipies smelt two items at once

### ISSUE THREAD

**Issue by RasmusKD** [WolfyScript/CustomCrafting-Wiki#44]
I made raw_gold_block smelt into gold_block, but after the first smelt it smelts 2 at once.

**Comment by RasmusKD** [comment]
https://user-images.githubusercontent.com/59487370/130409131-54bf08da-470f-4e37-be77-b879cd1c7143.mp4

**Comment by WolfyScript** [comment]
Is it related to issue #45, that you reported. 
If so, is it still happening if you just use CustomCrafting and WolfyUtilities on your server without McMMO?

**Comment by RasmusKD** [comment]
Its not related to 45, i can replicate it without mcmmo on the server
