### ISSUE TITLE
Console Error with CustomCrafting v2.16.0.0-beta3 on Paper 1.17.1

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [WolfyScript/CustomCrafting-Wiki#47]
**Describe the bug**
A console error appears when I run /CustomCrafting. This started occurring after I created a furnace recipe that used a custom Ore block from ItemsAdder and an MMOItems material item as the result. I then opened /CustomCrafting again and viewed the recipe list because I wanted to edit the recipe's tick length to 180 instead of 20. After that point is when the error started occurring.

**To Reproduce**
1. Have ItemsAdder & MMOItems on a Paper 1.17.1 server.
2. Create a furnace recipe using a custom ore block as your ingredient and an MMOItems material item as your result. The tick length should be 20 and exp is 1. Do Save As. My namespace & key were: material ruby
3. Open /CustomCrafting again and view either Recipe List or the one below it (I forget which I chose). 
4. Close it. 
5. Run command again. Error occurs.

**Expected behavior**
The console error to not appear and allow me to open the GUI.

**Screenshots**

**Server (please complete the following information):**
 - Server Software: Paper version git-Paper-202 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2406634)
 - Minecraft version ^
 - Java version Java 16

**Additional context**
Console Error: https://pastebin.com/855HFwCB
Server Log: https://pastebin.com/PPwNuZGs

**Comment by PiggiesGoSqueal** [comment]
I see you mentioned something about using a different version for ItemsAdder support for now. So I'll try that.

https://github.com/WolfyScript/CustomCrafting-Wiki/issues/46#issuecomment-904750198

**Comment by PiggiesGoSqueal** [comment]
Using CustomCrafting 1.7.1.3 for now seems to have solved it. 

I guess this bug report should be marked as duplicate of #46

**Comment by WolfyScript** [comment]
Ok, I see. The next update is going to fix it. It isn't linked to ItemsAdder or MMOItems... but it is an error I made in the code.

I am still looking for a solution for the ItemsAdder incompatibility, so for now even though this error is fixed you should still use 1.7.1.3.
