### ISSUE TITLE
Almost all my smithing recipies will not craft, 2-4 of them do work

### ISSUE THREAD

**Issue by LadyHaley** [WolfyScript/CustomCrafting-Wiki#48]
**Describe the bug**

The majority of my smithing recipes are just not working, even tho I made them all at the same time in the GUI with the same steps. I don't get how some could work but some could not. The Netherite Iron Sword and Netherite Gold Sword are working, I suspect maybe some of the others are working too but I cant craft past Iron so idk

**To Reproduce**
1. It was earlier this year but I used the gui to make the recipes
2. The items are all registered as custom items in CC
3. Only a handful of them will craft, the rest will not

**Expected behavior**

My Item to craft

**Screenshots**

**Server (please complete the following information):**
 - Server Software [e.g. Spigot, Paper, Velocity]
 - Minecraft version [e.g. 1.16.5]
 - Java version [e.g. Java 8, 11, 16]

Paper-783 (MC: 1.16.5)
Minecraft 1.16.5
Java 16

**Additional context**

I have remade the recipes from scratch in an effort to fix them with no luck.
Here is my zip file because I am at a loss for what is wrong.
[netherupgrade.zip](https://github.com/WolfyScript/CustomCrafting-Wiki/files/7093352/netherupgrade.zip)

**Comment by WolfyScript** [comment]
I looked through the files, and it seems like some items in the recipe are not saved as a reference.  
Meaning, they are not linked to a saved item, but instead are saved directly in the recipe.  
For each one, it looks like it's the addition (ingot) that is not correctly saved:
- craftironsword:
base: NETHERITE_SWORD (material no nbt. Shouldn't make issues)  
addition: gold ingot (direct item with nbt)
- craftgoldsword: 
base: netherupgrade:ironsword  
addition: gold ingot (direct item with nbt)
- craftdiamondsword:
base: netherupgrade:goldsword
addition: netherupgrade:diamondingot (Suddenly using the saved item!?)

Probable issue:  
Using the original ingots to craft the recipes works until you reach `craftdiamondsword`. That recipe requires the item you get via `/cc give`. 

Solutions:
- Make sure to only use the items from `/cc give` to create/recreate and later craft the recipe.
The items you get from the give command contain an ID that is checked upon crafting. If you use the original ones, they don't contain the ID and fail.
- Go through the files and replace items that are directly saved into the recipe with their namespaced key (Examples can be found in the correctly saved recipes). And use the items from `/cc give` to craft the recipes.

Recipes that have items that are not linked to the existing saved items:
- craftgoldsword (Result & addition are not referring to a saved item)
- craftironaxe (Base & Addition)
- craftironboots (Result, Base & Addition)
- craftironchestplate (Result, Base & Addition)
- craftironhelmet (Result, Base & Addition)
- craftironhoe (Result, Base & Addition)
- craftironleggings (Result & Addition)
- craftironpick (Result, Base & Addition)
- craftironshovel (Result, Base & Addition)
- craftironsword (Base & Addition)

**Comment by LadyHaley** [comment]
Okay, I will rework the recipies with all of this in mind, thank you
