### ISSUE TITLE
Dupe Items Glitch with Elite Crafting Table

### ISSUE THREAD

**Issue by wolf0023** [WolfyScript/CustomCrafting-Wiki#50]
**Describe the bug**
You can dupe any items with Elite Crafting Table

**To Reproduce**
1. Fill items in Elite Crafting Table
2. Take all items out of crafting table
3. You can get items but there will be some items in crafting table

**Video**
https://youtu.be/hIUlsJWMvlI

**Server (please complete the following information):**
 - Server Software [Paper-753 (MC: 1.16.5)]
 - Minecraft version [MC 1.16.5]
 - Java version [Java16]
 - CustomCrafting version [1.7.1.3]
 - WolfyUtilities version [1.7.3.0]

**Comment by WolfyScript** [comment]
oh no not this again... I will try to see if I can reproduce it and how I can fix it.

**Comment by WolfyScript** [comment]
I have been trying to reproduce it, but no luck. Do you have any other plugins installed that might interfere with it?

**Comment by wolf0023** [comment]
It has occurred only with customcrafting and wolfyutilities....

---------[Test Server's infos]---------
Server Software [Spigot]
Minecraft version [MC 1.16.5]
Java version [Java16]
CustomCrafting version [1.7.1.3f]
WolfyUtilities version [1.7.3.0]
----------------------------------------

**Comment by wolf0023** [comment]
It has occurred only with customcrafting and wolfyutilities too....

**≫ Test Server's Infos ≪**
Server Software [Spigot]
Minecraft version [MC 1.16.5]
Java version [Java16]
CustomCrafting version [1.7.1.3f]
WolfyUtilities version [1.7.3.0]
