### ISSUE TITLE
I'm unable to use the plugin.

### ISSUE THREAD

**Issue by Ant4All** [WolfyScript/CustomCrafting-Wiki#51]
I'm using minehut to host the server and I downloaded the plugins with minehut and yet it won't work. Its as if I don't have the plugins at all.

![notworkingsad](https://user-images.githubusercontent.com/90222549/132263464-89c6e8b9-6e28-482f-b0b5-e3b09f479462.PNG)

**Comment by WolfyScript** [comment]
Which version of CustomCrafting and WolfyUtilities do you use?
Note that the 1.7.x versions require Java 16 and may only work on 1.16+ servers.
If you are not able to use Java 16 please use CustomCrafting 1.6.6.0.1 and WolfyUtilities 1.6.4.2
