### ISSUE TITLE
CC Removed enchantment glint from items that have the glint but no enchantments on it

### ISSUE THREAD

**Issue by LadyHaley** [WolfyScript/CustomCrafting-Wiki#52]
**Describe the bug**
CC Removed enchantment glint from items that have the glint but no enchantments on it

**To Reproduce**
1. spawn an item with an enchantment glint
2. put the item in any of the guis for CC
3. no more enchantment glint
**Expected behavior**
The enchantment glint would stay, it helps to make custom items more distinct when using vanilla textures
**Screenshots**

**Server (please complete the following information):**
 - Server Software [e.g. Spigot, Paper, Velocity]
 - Minecraft version [e.g. 1.16.5]
 - Java version [e.g. Java 8, 11, 16]
Paper-783 (MC: 1.16.5)
Minecraft 1.16.5
Java 16

**Additional context**
This didn't used to be the case last year

**Comment by WolfyScript** [comment]
What does the original nbt of the item look like? Does it has like null set for the enchants?
I suspect that Bukkit does not support null enchants and therefor removes the glint.
Basically the moment you place the item into the GUI it is updated by bukkit, which removes the glint, because the item doesn't have any enchants.

**Comment by LadyHaley** [comment]
It used to work fine with CC last year, I'm not sure what could have changed to break it

**Comment by WolfyScript** [comment]
I assume that Bukkit or Minecraft changed something, because I didn't really change anything.
I encountered similar issues before where Bukkit no longer accepts setting custom entities on spawn eggs that are bound to a type. 
Unfortunately, I don't have control about that.

**Comment by LadyHaley** [comment]
I just checked, Mythic Mobs and Magic both also freak out when given the same item. as for the eggs, they both have custom eggs using the egg item I'm pretty sure, are you sure you cant have custom mob eggs?

**Comment by WolfyScript** [comment]
I think it's just when using for example creeper spawn eggs for another type of entity. Bukkit will instead convert the type of egg to the entity it contains.
I am closing this issue now, because there isn't a way I can fix it, unfortunately.
