### ISSUE TITLE
Hex Color Support 

### ISSUE THREAD

**Issue by Lordgatito** [WolfyScript/CustomCrafting-Wiki#54]
**Desc.**
I think we really need hex colors for names and lore, as they give a lot of variety to the eyes in terms of color and doesn't limit creativity when using them.

**Solution**
I'd recommend to make &# the prefix for this Hex colors (Ex: &#36ad93Epic sword), but if that's not the case, <#FFFFFF> and [#FFFFFF

**Reasons to make this a thing**

1.- Why not
2.- As I said, it gives variety in color names and lore
3.- Gives a more uniqueness to items basically making their color unique (Literally)

**Comment by WolfyScript** [comment]
I just checked as I thought I added already and it turns out I did indeed implemented it... but I used the format `&#(FFFFFF)` not sure why I add the brackets. I guess there was a reason I did it that way.

**Comment by Lordgatito** [comment]
Well, if it's possible, just suggest to change it to a simpler way like the ones I suggested, thanks for adding!
