### ISSUE TITLE
Anvil durability recipes not ignoring metadata and not repairing items.

### ISSUE THREAD

**Issue by Mnky313** [WolfyScript/CustomCrafting-Wiki#57]
**Describe the bug**
I cannot get the anvil repair recipes to function correctly, no matter what settings are selected it only accepts exact metadata (so the exact durability of the item I used in the recipe) and doesn't change durability when attempting to repair.

**To Reproduce**
create an anvil recipe on durability mode
attempt to use it
even with ignore meta it doesn't accept any different durability input
even when using the same durability item the durability remains unchanged.

**Expected behavior**
Ignore meta should accept any durability tool and should repair the item x amount (whatever set in the amount field)

**Screenshots**
![image](https://user-images.githubusercontent.com/23646586/133105336-9c627498-b9f3-4809-8f07-3b5000d412c0.png)

![image](https://user-images.githubusercontent.com/23646586/133105288-0e030499-de96-4c0e-81e4-ba68cb164807.png)
![image](https://user-images.githubusercontent.com/23646586/133105379-f2006c60-360f-47fd-bce1-01c6e80e0c11.png)

**Server (please complete the following information):**
Paper #255 1.17.1
Same issue is present with no other plugins or datapacks installed.

**Additional context**
I tried different tools as well and combining 2 different tools, no change.

**Comment by WolfyScript** [comment]
I can confirm that it doesn't repair it. Going to look into that.  
Regarding the recipe not accepting the differently damaged items... Try to create the recipe with an item that isn't damaged or has any other nbt data. 
How the ignore meta works is that it still checks the meta if the item that's set in the recipe contains any, but ignores it for those without any.

**Comment by Mnky313** [comment]
> I can confirm that it doesn't repair it. Going to look into that.
> Regarding the recipe not accepting the differently damaged items... Try to create the recipe with an item that isn't damaged or has any other nbt data.
> How the ignore meta works is that it still checks the meta if the item that's set in the recipe contains any, but ignores it for those without any.

Thanks, Thought I tried creating a recipe with an undamaged tool but guess not. Using an undamaged tool does let it accept other durabilities.

**Comment by WolfyScript** [comment]
Closing this as it is fixed in 2.16-beta5. Free version will still take a while.
