### ISSUE TITLE
Ability to change generic.attack_damage

### ISSUE THREAD

**Issue by ColonelKai** [WolfyScript/CustomCrafting-Wiki#59]
**Describe the solution you'd like**
Ability to change the `generic.attack_damage` (this thing) 
![image](https://user-images.githubusercontent.com/59742334/133508493-9ce88996-a3b4-4259-9cb5-2a6cfca02d89.png)
as opposed to just being able to put modifiers on (like the +10% damage kind of stuff). I'm sorry if there is a way to do this I just couldn't find it.

**Comment by WolfyScript** [comment]
Unfortunately attributes cannot be changed by items, as they are not actually part of the item.
The attributes are part of the entity. For example `generic.attack_damage` varies depending on the entity and the modifiers change the behavior.
The wiki has a lot of useful information about that https://minecraft.fandom.com/wiki/Attribute

**Comment by ColonelKai** [comment]
Does a, for example, 10% damage modifier when on main hand, increase the base attack damage of a sword?
ex. an iron sword has 6 attack damage, when I apply a +10% Generic Attack Modifier, does that increase it to a 6.6?

**Comment by WolfyScript** [comment]
I think the base is 2 so it would result in 6.2... I think. 
I don't use modifiers very often, so perhaps there are some tutorials on yt, etc. that could help you and explain it a bit better.

**Comment by ColonelKai** [comment]
Thanks for the help!
