### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by chris998** [WolfyScript/CustomCrafting-Wiki#6]
https://pastebin.com/yfnb2vq5

I have the Lastest of both plugin Wolfy and custom

**Comment by WolfyScript** [comment]
ok, I will have a look at that. WolfyUtilities and CustomCrafting are currently changing a lot anyway so that error will be most likely be fixed in future updates.

**Comment by WolfyScript** [comment]
Kinda forgot to close the issue... error should be fixed.
