### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Levy-Y** [WolfyScript/CustomCrafting-Wiki#60]
I was making recipes on my server, but i noticed somethiing gave me an error

I don't know what does it, but it seemes like its something with the Elite Workbench data

![error](https://user-images.githubusercontent.com/65444028/133907169-919fa34f-aca8-459e-b04e-65412c51e771.PNG)

 - Server Software: Spigot
 - Minecraft version: 1.17
 - Java version: 16

**Comment by WolfyScript** [comment]
Did you create an Elite Crafting Table or recipes for it?
