### ISSUE TITLE
Create recipe that has multiple items with the cauldron

### ISSUE THREAD

**Issue by YKDZ** [WolfyScript/CustomCrafting-Wiki#61]
**Describe the solution you'd like**
I want to be able to create a cauldron recipe with multiple input items. For example, put apples and gold ingots into cauldron and output golden apples after a period of time.

**Comment by WolfyScript** [comment]
Currently, the cauldron recipes use the ingredient variants for that.
You can shift + right-click on the ingredient slot to set multiple items.

**Comment by YKDZ** [comment]
> Currently, the cauldron recipes use the ingredient variants for that.
> You can shift + right-click on the ingredient slot to set multiple items.

Oh, sorry. I didn't know that. Thank you for telling me

**Comment by WolfyScript** [comment]
No problem. The cauldron recipes are different from the other recipes. I might add multiple slots to the creator, so it is more intuitive.
