### ISSUE TITLE
My server just... stops loading???

### ISSUE THREAD

**Issue by Kierancraft** [WolfyScript/CustomCrafting-Wiki#63]
**Describe the bug**
My server is running java 16, the latest version of wolfyutilities, and customcrafting, alongside some other plugins. When im starting my server, it gets to the Loading Recipes & Items - - - - [Local Storage] - - - - (and then my files) but then just... stops loading? the cpu goes to 0, the ram settles, and the server doesnt continue or finish starting???? 

**To Reproduce**
I DONT KNOW

**Expected behavior**
I expected it to load and work as intended like it was when I was using an earlier version (1.6.smthn idk) which also stopped working. The only plugin I have added since is skript (which I assume is compatible because why wouldn't it be?)

**Screenshots**
![image](https://user-images.githubusercontent.com/58084083/134268636-66b2b48e-fd1c-4558-8dc3-468f8969619d.png)

**Server (please complete the following information):**
 - Server Software Paper 1.16.5
 - Minecraft version 1.16.5
 - Java version 16

**Additional context**
I can upload my plugin list if it helps? PLEASE HELP ME

**Comment by WolfyScript** [comment]
That error is weird. It might be the recipe book, but there isn't any indication nor error.
Since you said you are using 1.6.x... I would recommend that you update to the latest versions (CC 1.7.1.3 & WU 1.7.3.0).
