### ISSUE TITLE
Fresh Install. CC isn't loaded correctly?

### ISSUE THREAD

**Issue by SoraShiunin** [WolfyScript/CustomCrafting-Wiki#7]
Version before overhaul worked fine. This one does not load.
```

04.02 14:04:33 [Server] Server thread/ERROR Could not load 'plugins/customcrafting-1.6.5.0.jar' in folder 'plugins'
04.02 14:04:33 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/wolfyscript/utilities/util/Keyed
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:332) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
04.02 14:04:33 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/wolfyscript/utilities/util/Keyed
04.02 14:04:33 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO ... 7 more
04.02 14:04:33 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.wolfyscript.utilities.util.Keyed
04.02 14:04:33 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[custom.jar:2997-Spigot-89d6047-c3e684e]
04.02 14:04:33 [Server] INFO ... 7 more
04.02 14:04:33 [Server] Server thread/WARN Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
04.02 14:04:35 [Server] Server thread/WARN Legacy plugin ActionHealth v3.5.2 does not specify an api-version.
```

**Comment by WolfyScript** [comment]
It seems that you do not have the latest version of WolfyUtilities, which is required.

**Comment by SoraShiunin** [comment]
![Screenshot_617](https://user-images.githubusercontent.com/23641964/107123760-46ac9d00-6897-11eb-83cf-beb07249e673.png)
This is the version I have, latest on Spigot.

**Comment by WolfyScript** [comment]
ok yeah I got some more reports of this error. 
Somehow it doesn't find the file even though it exists inside the jar.

I will rebuild it soon and reupload the file. I hope that it will fix it.

You can also try if it might be caused by another plugin by just installing wu and cc.

**Comment by WolfyScript** [comment]
Is this error still happening with the latest WolfyUtilities?

I got some other reports and the common factor was MMOItems. Do you have that plugin? and if so which version?

**Comment by SoraShiunin** [comment]
Hi, sorry I forgot this. No I do not have mmoitems. The only thing I can think of that could be imcopatible would be citizens or FAWE.

**Comment by WolfyScript** [comment]
hmm ok. 
I am so confused about this update... I tested it on my local server, hosted server and it all worked fine.
I don't really believe it are other plugins in then.
However, are you able to test it with just WU and CC installed?
If it still doesn't work, which server software are you using? like paper, spigot or any other kind of software.

**Comment by Wertik** [comment]
@WolfyScript how are you loading the utils, relying on spigot's dependency system? This might be just an issue of order. If the Class loader loads depending plugins first, WolfyUtils is not gonna be present for them.

This could be an issue with spigot's dependency system and it being unable to resolve some cyclic or more complex deps.

**Comment by WolfyScript** [comment]
@Wertik CustomCrafting has WolfyUtilities as a soft-dependency, so I can print a custom message if it is not installed.
But if soft-depend doesn't work as it should I will change it back to depend.
Next WolfyUtilities update I will add a loadbefore for the time being. That will show if it is a depend problem.

**Comment by WolfyScript** [comment]
Ok I posted an update for WolfyUtilities v1.6.3.8 that hopefully fixes this issue.
Let me know if the issue is resolved.

**Comment by iFyrax** [comment]
- Java version : Java 8
- Minecraft version : 1.16.5
- Server software : Paper 
- Custom-Crafting 16.5.1, WU 1.6.3.8
https://pastebin.com/smJjmmJK

**Comment by iFyrax** [comment]
https://pastebin.com/ZxLyt45D -> when i do : /customcrafting

**Comment by iFyrax** [comment]
https://pastebin.com/3CSeQJW0 -> error with WolfyUtilities

**Comment by WolfyScript** [comment]
The original bug was fixed. If you have another error please open a new issue.
