### ISSUE TITLE
Recipes using custom items not working

### ISSUE THREAD

**Issue by Wall0fFlesh** [WolfyScript/CustomCrafting-Wiki#73]
**Describe the bug**
I was using an old version of the plugin (1.6.5.1) when i decided to use the latest version because cauldrons recipes didnt work, after updating it, all workbench recipes stop working and i cant use them. (Im also using the latest version of WolfyUtilities) I tried to create a new recipe but it dont work either (i remade the recipes multiple times)

**To Reproduce**
1. Try to craft the item
2. The item dont shows up

**Expected behavior**
The item would be crafted

**Screenshots**

![Screen_issue_workbench_1](https://user-images.githubusercontent.com/94698155/142723653-4e91a555-a5cd-466a-8261-a51199e0761b.png)
![Screen_issue_workbench_2](https://user-images.githubusercontent.com/94698155/142723679-c0467c49-275f-4ae4-b635-2c13f4e01b91.png)
![Screen_issue_workbench_3](https://user-images.githubusercontent.com/94698155/142723688-bd8772b8-863e-468d-889c-b1d4a0cf29d8.png)
![Screen_issue_workbench_4](https://user-images.githubusercontent.com/94698155/142723696-3180fe0f-b676-4177-baf8-747f91040667.png)

**Server (please complete the following information):**
 - Server Software : Paper 1.17.1
 - Minecraft version : 1.17.1
 - Java version : Java 16

**Additional context**
Only workbench recipes dont work, other works perfectly fine

**Comment by Wall0fFlesh** [comment]
Actually, the bug isnt related to the workbench recipes but related to all the recipes using custom items from the item creator

**Comment by WolfyScript** [comment]
Can you check if that happens with WolfyUtilities 1.7.7.0?  
Might be the new update causing these issues. I will definitely look into that one.

**Comment by Wall0fFlesh** [comment]
ok so, i created a test server with only custom crafting and wolfyUtilities plugins to be sure that the issue isnt related to any incompatibilities. Ive tested both versions (WolfyUtilities 1.7.7.0 and 1.7.8.0), the same problem happens with WolfyUtilities 1.7.8.0 but the crafts worked with WolfyUtilities 1.7.7.0

**Comment by WolfyScript** [comment]
~~Can you send one of the JSON files of your Custom Items?~~

Edit: I found the issues, that are causing this. The new system in WU 1.7.8.0 still had some problems reading and converting old data. I try to have a fix out very soon. For now, I recommend you use WU 1.7.7.0.
