### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by soupcoup** [WolfyScript/CustomCrafting-Wiki#75]
are there plans to update to 1.18? or a snapshot i could use?

**Comment by WolfyScript** [comment]
Using WolfyUtilities 1.8.0.0 you should be able to run it on 1.18. There might be some issues, but unfortunately those are on the side of Spigot. 
At the current moment, I recommend not updating to 1.18, as it will still take a bit till it's stable. Instead, you could make a test server, to migrate your server, and then if 1.18 is stable enough you are ready to go.
